//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcuaDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIRECION()
        {
            this.PROVEEDORs = new HashSet<PROVEEDOR>();
            this.USUARIOs = new HashSet<USUARIO>();
        }
    
        public int DIR_ID { get; set; }
        public int CIU_ID { get; set; }
        public string DIR_CALLE_P { get; set; }
        public string DIR_CALLE_S { get; set; }
        public string DIR_NUM_C { get; set; }
        public string DIR_DETALLE { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR> PROVEEDORs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIOs { get; set; }
    }
}
