//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcuaDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public int PRV_ID { get; set; }
        public int DIR_ID { get; set; }
        public string PRV_NOMBRE { get; set; }
        public string PRV_RUC { get; set; }
        public string PRV_TELEFONO { get; set; }
        public string PRV_EMAIL { get; set; }
        public string PRV_DESCRIPCION { get; set; }
        public string PRV_CONTRASENA { get; set; }
    
        public virtual DIRECION DIRECION { get; set; }
    }
}
